name: plateforme_stagiaires
description: "Application Flutter pour le carnet de stage et le covoiturage"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  geofence_service: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  path_provider: 2.1.6
  connectivity_plus: ^5.0.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  