// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi-4KjKblxkk7MRUzTbbB-gBLTTBJWrfI',
    appId: '1:692123570392:web:55c714a7f9a618cd4c87ad',
    messagingSenderId: '692123570392',
    projectId: 'mon-projet-st',
    authDomain: 'mon-projet-st.firebaseapp.com',
    storageBucket: 'mon-projet-st.firebasestorage.app',
    measurementId: 'G-JBKSF4QE8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKWJx1rlAgMPzYACWa7Gd8MGHUWYCkNY',
    appId: '1:692123570392:android:42a2aad0b1232b9b4c87ad',
    messagingSenderId: '692123570392',
    projectId: 'mon-projet-st',
    storageBucket: 'mon-projet-st.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrtsA0jYGRbnrei_IMrvECNGE2VmcLAo',
    appId: '1:692123570392:ios:268dff530004dbee4c87ad',
    messagingSenderId: '692123570392',
    projectId: 'mon-projet-st',
    storageBucket: 'mon-projet-st.firebasestorage.app',
    iosBundleId: 'com.example.plateformeStagiaires',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrtsA0jYGRbnrei_IMrvECNGE2VmcLAo',
    appId: '1:692123570392:ios:268dff530004dbee4c87ad',
    messagingSenderId: '692123570392',
    projectId: 'mon-projet-st',
    storageBucket: 'mon-projet-st.firebasestorage.app',
    iosBundleId: 'com.example.plateformeStagiaires',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi-4KjKblxkk7MRUzTbbB-gBLTTBJWrfI',
    appId: '1:692123570392:web:3b852ee77a4ec7a44c87ad',
    messagingSenderId: '692123570392',
    projectId: 'mon-projet-st',
    authDomain: 'mon-projet-st.firebaseapp.com',
    storageBucket: 'mon-projet-st.firebasestorage.app',
    measurementId: 'G-K8LN5JJMTR',
  );
}
